--
-- PostgreSQL database dump
--

-- Dumped from database version 14.12
-- Dumped by pg_dump version 16.3

-- Started on 2024-07-17 17:01:31

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 211 (class 1259 OID 16485)
-- Name: car; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.car (
    id bigint NOT NULL,
    car_age integer,
    car_brand character varying(255),
    car_generation character varying(255),
    car_mileage integer,
    car_model character varying(255),
    car_shop_id bigint,
    car_condition character varying(255),
    car_cost character varying(255),
    sales boolean
);


ALTER TABLE public.car OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16484)
-- Name: car_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.car ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 16396)
-- Name: car_shop; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.car_shop (
    id bigint NOT NULL,
    car_shop_address character varying(255),
    car_shop_name character varying(255)
);


ALTER TABLE public.car_shop OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16497)
-- Name: car_shop_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.car_shop ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_shop_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3315 (class 0 OID 16485)
-- Dependencies: 211
-- Data for Name: car; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.car (id, car_age, car_brand, car_generation, car_mileage, car_model, car_shop_id, car_condition, car_cost, sales) VALUES (20, 5, 'BMW', 'F90', 80000, 'M5', NULL, 'б/у', '70000', false);
INSERT INTO public.car (id, car_age, car_brand, car_generation, car_mileage, car_model, car_shop_id, car_condition, car_cost, sales) VALUES (19, 1, 'Toyota', 'VIII(XV70)', 100, 'Camry 3.5', 1, 'new', '30700', true);
INSERT INTO public.car (id, car_age, car_brand, car_generation, car_mileage, car_model, car_shop_id, car_condition, car_cost, sales) VALUES (21, 3, 'Porsche', '(PO536)', 50000, 'Cayenne', 18, 'б/у', '49700', true);
INSERT INTO public.car (id, car_age, car_brand, car_generation, car_mileage, car_model, car_shop_id, car_condition, car_cost, sales) VALUES (1, 1, 'Mercedes-Benz', 'W223', 50, 'S-class', 1, 'new', '200000', false);


--
-- TOC entry 3313 (class 0 OID 16396)
-- Dependencies: 209
-- Data for Name: car_shop; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.car_shop (id, car_shop_address, car_shop_name) VALUES (1, 'st.Yanki Luchiny,h.52,f.25,c.Saint-Petersburg', 'АвтоЛюкс');
INSERT INTO public.car_shop (id, car_shop_address, car_shop_name) VALUES (3, 'st.Yanki Luchiny,h.52,f.25,c.Saint-Petersburg', 'LamoEsthetics');
INSERT INTO public.car_shop (id, car_shop_address, car_shop_name) VALUES (18, 'st.Yanki Luchiny,h.52,f.25,c.Saint-Petersburg', 'LamoEsthetics');


--
-- TOC entry 3323 (class 0 OID 0)
-- Dependencies: 210
-- Name: car_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.car_id_seq', 22, true);


--
-- TOC entry 3324 (class 0 OID 0)
-- Dependencies: 212
-- Name: car_shop_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.car_shop_id_seq', 18, true);


--
-- TOC entry 3172 (class 2606 OID 16491)
-- Name: car car_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.car
    ADD CONSTRAINT car_pkey PRIMARY KEY (id);


--
-- TOC entry 3170 (class 2606 OID 16400)
-- Name: car_shop car_shop_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.car_shop
    ADD CONSTRAINT car_shop_pkey PRIMARY KEY (id);


--
-- TOC entry 3173 (class 2606 OID 16492)
-- Name: car fklwwe2il2qrnmh8m8bs9y9ltu9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.car
    ADD CONSTRAINT fklwwe2il2qrnmh8m8bs9y9ltu9 FOREIGN KEY (car_shop_id) REFERENCES public.car_shop(id);


--
-- TOC entry 3322 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2024-07-17 17:01:32

--
-- PostgreSQL database dump complete
--

